spring.application.name=honnebutton
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/honnebutton}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:honneuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:honnepass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always